### ISSUE TITLE
Fails to encode a big string

### ISSUE THREAD

**Issue by niahoo** [supernintendo/peon#6]
Hey, I added a new test case here : https://github.com/niahoo/eon/commit/abd9d1b5a65dcc731c4fcf0e9f735b6bc5717fac

It fails. Basically, `Macro.to_string` will not write the full representation of big strings like `%{ foo: String.duplicate("Elixir", 10000) }`.

I have no idea how to fix that. Maybe implement another `to_string` ?

**Comment by supernintendo** [comment]
Good catch. I wasn't aware that `Macro.to_string` cuts off large strings (if you look at the output file it doesn't even contain the remaining part of the string after the concat operator). There are probably good reasons for this, like memory concerns. I'll do some further digging and report on what I find.

Thanks!

**Comment by supernintendo** [comment]
@niahoo The way `Macro.to_string` formats strings changed since I wrote this library. If you run your failing test on Elixir 1.4.0, it passes as the entire string is output. There doesn't appear to be a way to provide an option to `Macro.to_string` to avoid limiting the number of characters that are output for strings the same way you would with `IO.inspect`. I need to investigate a bit more to see when this change was made and if it's a design choice on the part of the core Elixir team or a bug. I'll post updates in this issue as I have them.

**Comment by niahoo** [comment]
Ok so that's why the library enforces 1.4 version.
Thank you for taking time, but don't worry for me, I have a simple workaround with json.

**Comment by supernintendo** [comment]
Fixed in Elixir 1.6.5 https://github.com/elixir-lang/elixir/issues/7545.
